// Decompiled with JetBrains decompiler
// Type: Battle_ChainSplash
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x2000291")]
[AddComponentMenu("UI/Drafts/Battle_ChainSplash")]
public class Battle_ChainSplash : UIDraft
{
  [Token(Token = "0x4000ABA")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public RawImage SplashImage;

  [Token(Token = "0x6000DAD")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public Battle_ChainSplash()
  {
  }
}
