// Decompiled with JetBrains decompiler
// Type: CmnBtn
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x2000296")]
[AddComponentMenu("UI/Drafts/CmnBtn")]
public class CmnBtn : UIDraft
{
  [Token(Token = "0x4000AC9")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text;

  [Token(Token = "0x6000DCC")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public CmnBtn()
  {
  }
}
