// Decompiled with JetBrains decompiler
// Type: EventTest
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002A3")]
[AddComponentMenu("UI/Drafts/EventTest")]
public class EventTest : UIDraft
{
  [Token(Token = "0x4000AE5")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public RawImage RawImage;

  [Token(Token = "0x6000E0F")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public EventTest()
  {
  }
}
