// Decompiled with JetBrains decompiler
// Type: PlayerStatus
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002C5")]
[AddComponentMenu("UI/Drafts/PlayerStatus")]
public class PlayerStatus : UIDraft
{
  [Token(Token = "0x4000B74")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_PlayerName;
  [Token(Token = "0x4000B75")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Text Text_LevelNum;
  [Token(Token = "0x4000B76")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Text Text_Point_Current;
  [Token(Token = "0x4000B77")]
  [FieldOffset(Offset = "0x18")]
  [UIDraft.AutoGenerated]
  public Text Text_Point_Max;
  [Token(Token = "0x4000B78")]
  [FieldOffset(Offset = "0x1C")]
  [UIDraft.AutoGenerated]
  public Text Text_Timer;
  [Token(Token = "0x4000B79")]
  [FieldOffset(Offset = "0x20")]
  [UIDraft.AutoGenerated]
  public Text Text_KakinItemNum;
  [Token(Token = "0x4000B7A")]
  [FieldOffset(Offset = "0x24")]
  [UIDraft.AutoGenerated]
  public Text Text_GoldNum;
  [Token(Token = "0x4000B7B")]
  [FieldOffset(Offset = "0x28")]
  [UIDraft.AutoGenerated]
  public Slider Gauge_EXP;
  [Token(Token = "0x4000B7C")]
  [FieldOffset(Offset = "0x2C")]
  [UIDraft.AutoGenerated]
  public Slider Gauge_Shutsugeki;

  [Token(Token = "0x6000E7A")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public PlayerStatus()
  {
  }
}
