// Decompiled with JetBrains decompiler
// Type: Quest_ExitConfirm
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002C8")]
[AddComponentMenu("UI/Drafts/Quest_ExitConfirm")]
public class Quest_ExitConfirm : UIDraft
{
  [Token(Token = "0x4000B85")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000B86")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Button Btn_No;
  [Token(Token = "0x4000B87")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Button Btn_Yes;

  [Token(Token = "0x6000E7E")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public Quest_ExitConfirm()
  {
  }
}
