// Decompiled with JetBrains decompiler
// Type: QuestList_Item
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002C7")]
[AddComponentMenu("UI/Drafts/QuestList_Item")]
public class QuestList_Item : UIDraft
{
  [Token(Token = "0x4000B81")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Image Clear;
  [Token(Token = "0x4000B82")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Text Text_QuestName;
  [Token(Token = "0x4000B83")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Text Text_PointNum;
  [Token(Token = "0x4000B84")]
  [FieldOffset(Offset = "0x18")]
  [UIDraft.AutoGenerated]
  public Text Text_Point;

  [Token(Token = "0x6000E7D")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public QuestList_Item()
  {
  }
}
