// Decompiled with JetBrains decompiler
// Type: Quest_MoveUnit
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using System;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002C9")]
[AddComponentMenu("UI/Drafts/Quest_MoveUnit")]
public class Quest_MoveUnit : UIDraft
{
  [Token(Token = "0x4000B88")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public RectTransform VirtualStick;
  [Token(Token = "0x4000B89")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public RectTransform VirtualStickBG;
  [Token(Token = "0x4000B8A")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public RectTransform VirtualStickFG;
  [Token(Token = "0x4000B8B")]
  [FieldOffset(Offset = "0x18")]
  [UIDraft.AutoGenerated]
  public RectTransform TouchArea;
  [Token(Token = "0x4000B8C")]
  [FieldOffset(Offset = "0x1C")]
  [UIDraft.AutoGenerated]
  public Button Btn_OK;
  [Token(Token = "0x4000B8D")]
  [FieldOffset(Offset = "0x20")]
  [UIDraft.AutoGenerated]
  public Button Btn_Cancel;
  [Token(Token = "0x4000B8E")]
  [FieldOffset(Offset = "0x24")]
  public Quest_MoveUnit.ButtonClickEvent OnClickOK;
  [Token(Token = "0x4000B8F")]
  [FieldOffset(Offset = "0x28")]
  public Quest_MoveUnit.ButtonClickEvent OnClickCancel;
  [Token(Token = "0x4000B90")]
  [FieldOffset(Offset = "0x2C")]
  [NonSerialized]
  public Transform CameraTransform;
  [Token(Token = "0x4000B91")]
  [FieldOffset(Offset = "0x30")]
  private bool mTouched;
  [Token(Token = "0x4000B92")]
  [FieldOffset(Offset = "0x34")]
  private Vector3 mTouchStart;
  [Token(Token = "0x4000B93")]
  [FieldOffset(Offset = "0x40")]
  private Vector3 mTouchPos;
  [Token(Token = "0x4000B94")]
  [FieldOffset(Offset = "0x4C")]
  private Vector3 mVelocity;

  [Token(Token = "0x170001BC")]
  public Vector2 Velocity
  {
    [Token(Token = "0x6000E7F"), Address(RVA = "0x11D6EA0", Offset = "0x11D5CA0", VA = "0x111D6EA0")] get
    {
      return new Vector2();
    }
  }

  [Token(Token = "0x6000E80")]
  [Address(RVA = "0x8CC240", Offset = "0x8CB040", VA = "0x108CC240")]
  private void OnEnable()
  {
  }

  [Token(Token = "0x6000E81")]
  [Address(RVA = "0x11D6630", Offset = "0x11D5430", VA = "0x111D6630")]
  private void Start()
  {
  }

  [Token(Token = "0x6000E82")]
  [Address(RVA = "0x11D6B00", Offset = "0x11D5900", VA = "0x111D6B00")]
  private void Update()
  {
  }

  [Token(Token = "0x6000E83")]
  [Address(RVA = "0x11D65D0", Offset = "0x11D53D0", VA = "0x111D65D0")]
  public void ShowButtons(bool show)
  {
  }

  [Token(Token = "0x6000E84")]
  [Address(RVA = "0x11D6E50", Offset = "0x11D5C50", VA = "0x111D6E50")]
  public Quest_MoveUnit()
  {
  }

  [Token(Token = "0x20002CA")]
  public delegate void ButtonClickEvent();
}
