// Decompiled with JetBrains decompiler
// Type: SelectArea
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002CF")]
[AddComponentMenu("UI/Drafts/SelectArea")]
public class SelectArea : UIDraft
{
  [Token(Token = "0x4000BA6")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_AreaName;
  [Token(Token = "0x4000BA7")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [Token(Token = "0x4000BA8")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Button Area_Item;
  [Token(Token = "0x4000BA9")]
  [FieldOffset(Offset = "0x18")]
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [Token(Token = "0x4000BAA")]
  [FieldOffset(Offset = "0x1C")]
  [UIDraft.AutoGenerated]
  public Button Btn_BackWorld;

  [Token(Token = "0x6000EA5")]
  [Address(RVA = "0x44BFA0", Offset = "0x44ADA0", VA = "0x1044BFA0")]
  public SelectArea()
  {
  }
}
