// Decompiled with JetBrains decompiler
// Type: Title
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x20002DF")]
[AddComponentMenu("UI/Drafts/Title")]
public class Title : UIDraft
{
  [Token(Token = "0x4000BED")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Button Button_TapStart;
  [Token(Token = "0x4000BEE")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Button Button_NewGame;

  [Token(Token = "0x6000EF3")]
  [Address(RVA = "0x2ACF80", Offset = "0x2ABD80", VA = "0x102ACF80")]
  public Title()
  {
  }
}
