// Decompiled with JetBrains decompiler
// Type: Win_Btn_YN_FL_C
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x200030F")]
[AddComponentMenu("UI/Drafts/Win_Btn_YN_FL_C")]
public class Win_Btn_YN_FL_C : UIDraft
{
  [Token(Token = "0x4000C95")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000C96")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Button Btn_No;
  [Token(Token = "0x4000C97")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Button Btn_Yes;

  [Token(Token = "0x6000FEC")]
  [Address(RVA = "0x2ACF80", Offset = "0x2ABD80", VA = "0x102ACF80")]
  public Win_Btn_YN_FL_C()
  {
  }
}
