// Decompiled with JetBrains decompiler
// Type: Win_SysMessage_Flx
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x2000314")]
[AddComponentMenu("UI/Drafts/Win_SysMessage_Flx")]
public class Win_SysMessage_Flx : UIDraft
{
  [Token(Token = "0x4000CB5")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000CB6")]
  [FieldOffset(Offset = "0x10")]
  public Image Bg;
  [Token(Token = "0x4000CB7")]
  [FieldOffset(Offset = "0x14")]
  public AnimationCurve AnimationCurve;
  [Token(Token = "0x4000CB8")]
  [FieldOffset(Offset = "0x18")]
  public float Delay;
  [Token(Token = "0x4000CB9")]
  [FieldOffset(Offset = "0x1C")]
  public float Duration;
  [Token(Token = "0x4000CBA")]
  [FieldOffset(Offset = "0x20")]
  private bool m_StartAnimation;
  [Token(Token = "0x4000CBB")]
  [FieldOffset(Offset = "0x24")]
  private float m_Factor;
  [Token(Token = "0x4000CBC")]
  [FieldOffset(Offset = "0x28")]
  private float m_Time;
  [Token(Token = "0x4000CBD")]
  [FieldOffset(Offset = "0x2C")]
  private bool m_AutoClose;
  [Token(Token = "0x4000CBE")]
  [FieldOffset(Offset = "0x30")]
  private float m_AutoCloseTime;
  [Token(Token = "0x4000CBF")]
  [FieldOffset(Offset = "0x34")]
  private UIWindow m_Window;

  [Token(Token = "0x170001DA")]
  public UIWindow window
  {
    [Token(Token = "0x6001000"), Address(RVA = "0x12B3420", Offset = "0x12B2220", VA = "0x112B3420")] get
    {
      return (UIWindow) null;
    }
  }

  [Token(Token = "0x6001001")]
  [Address(RVA = "0x2781C0", Offset = "0x276FC0", VA = "0x102781C0")]
  private void Awake()
  {
  }

  [Token(Token = "0x6001002")]
  [Address(RVA = "0x2781C0", Offset = "0x276FC0", VA = "0x102781C0")]
  private void Start()
  {
  }

  [Token(Token = "0x6001003")]
  [Address(RVA = "0x12B2E50", Offset = "0x12B1C50", VA = "0x112B2E50")]
  public void Initialize(bool isBg, float alpha = 0.0f)
  {
  }

  [Token(Token = "0x6001004")]
  [Address(RVA = "0x12B30B0", Offset = "0x12B1EB0", VA = "0x112B30B0")]
  private void Update()
  {
  }

  [Token(Token = "0x6001005")]
  [Address(RVA = "0x12B3080", Offset = "0x12B1E80", VA = "0x112B3080")]
  public void StartAnim()
  {
  }

  [Token(Token = "0x6001006")]
  [Address(RVA = "0x12B2D80", Offset = "0x12B1B80", VA = "0x112B2D80")]
  public void AutoClose(float time)
  {
  }

  [Token(Token = "0x6001007")]
  [Address(RVA = "0x12B2DA0", Offset = "0x12B1BA0", VA = "0x112B2DA0")]
  public void BeginClose()
  {
  }

  [Token(Token = "0x6001008")]
  [Address(RVA = "0x12B3000", Offset = "0x12B1E00", VA = "0x112B3000")]
  private void OnWindowClose(UIWindow window)
  {
  }

  [Token(Token = "0x6001009")]
  [Address(RVA = "0x12B32C0", Offset = "0x12B20C0", VA = "0x112B32C0")]
  public Win_SysMessage_Flx()
  {
  }
}
