// Decompiled with JetBrains decompiler
// Type: Win_Btn_DecideCancel_FL_Check_C
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using System;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x200030B")]
[AddComponentMenu("UI/Drafts/Win_Btn_DecideCancel_FL_Check_C")]
public class Win_Btn_DecideCancel_FL_Check_C : UIDraft
{
  [Token(Token = "0x4000C84")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000C85")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Toggle Toggle;
  [Token(Token = "0x4000C86")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Button Btn_Cancel;
  [Token(Token = "0x4000C87")]
  [FieldOffset(Offset = "0x18")]
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [Token(Token = "0x4000C88")]
  [FieldOffset(Offset = "0x1C")]
  public UIUtility.DialogResultEvent OnClickYes;
  [Token(Token = "0x4000C89")]
  [FieldOffset(Offset = "0x20")]
  public UIUtility.DialogResultEvent OnClickNo;
  [Token(Token = "0x4000C8A")]
  [FieldOffset(Offset = "0x24")]
  [NonSerialized]
  public string ConfirmID;

  [Token(Token = "0x6000FDC")]
  [Address(RVA = "0x12B1B00", Offset = "0x12B0900", VA = "0x112B1B00")]
  private void OnWindowClose(UIWindow window)
  {
  }

  [Token(Token = "0x6000FDD")]
  [Address(RVA = "0x12B1880", Offset = "0x12B0680", VA = "0x112B1880")]
  private void BeginClose()
  {
  }

  [Token(Token = "0x6000FDE")]
  [Address(RVA = "0x12B1920", Offset = "0x12B0720", VA = "0x112B1920")]
  private void OnClickButton(GameObject obj)
  {
  }

  [Token(Token = "0x6000FDF")]
  [Address(RVA = "0x12B1790", Offset = "0x12B0590", VA = "0x112B1790")]
  private void Awake()
  {
  }

  [Token(Token = "0x6000FE0")]
  [Address(RVA = "0x2ACF80", Offset = "0x2ABD80", VA = "0x102ACF80")]
  public Win_Btn_DecideCancel_FL_Check_C()
  {
  }
}
