// Decompiled with JetBrains decompiler
// Type: Win_Btn_Decide_Title_Flx
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x200030D")]
[AddComponentMenu("UI/Drafts/Win_Btn_Decide_Title_Flx")]
public class Win_Btn_Decide_Title_Flx : UIDraft
{
  [Token(Token = "0x4000C8E")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Title;
  [Token(Token = "0x4000C8F")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000C90")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [Token(Token = "0x4000C91")]
  [FieldOffset(Offset = "0x18")]
  public UIUtility.DialogResultEvent OnClickYes;

  [Token(Token = "0x6000FE6")]
  [Address(RVA = "0x12B20D0", Offset = "0x12B0ED0", VA = "0x112B20D0")]
  private void OnWindowClose(UIWindow window)
  {
  }

  [Token(Token = "0x6000FE7")]
  [Address(RVA = "0x12B1F00", Offset = "0x12B0D00", VA = "0x112B1F00")]
  public void BeginClose()
  {
  }

  [Token(Token = "0x6000FE8")]
  [Address(RVA = "0x12B1FB0", Offset = "0x12B0DB0", VA = "0x112B1FB0")]
  private void OnClickButton(GameObject obj)
  {
  }

  [Token(Token = "0x6000FE9")]
  [Address(RVA = "0x12B1E60", Offset = "0x12B0C60", VA = "0x112B1E60")]
  private void Awake()
  {
  }

  [Token(Token = "0x6000FEA")]
  [Address(RVA = "0x2ACF80", Offset = "0x2ABD80", VA = "0x102ACF80")]
  public Win_Btn_Decide_Title_Flx()
  {
  }
}
