// Decompiled with JetBrains decompiler
// Type: Win_Message_Flx
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x2000313")]
[AddComponentMenu("UI/Drafts/Win_Message_Flx")]
public class Win_Message_Flx : UIDraft
{
  [Token(Token = "0x4000CB4")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;

  [Token(Token = "0x6000FFF")]
  [Address(RVA = "0x2ACF80", Offset = "0x2ABD80", VA = "0x102ACF80")]
  public Win_Message_Flx()
  {
  }
}
