// Decompiled with JetBrains decompiler
// Type: Win_Btn_DecideCancel_FL_C
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x200030A")]
[AddComponentMenu("UI/Drafts/Win_Btn_DecideCancel_FL_C")]
public class Win_Btn_DecideCancel_FL_C : UIDraft
{
  [Token(Token = "0x4000C7C")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000C7D")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Button Btn_Cancel;
  [Token(Token = "0x4000C7E")]
  [FieldOffset(Offset = "0x14")]
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [Token(Token = "0x4000C7F")]
  [FieldOffset(Offset = "0x18")]
  public Text Txt_No;
  [Token(Token = "0x4000C80")]
  [FieldOffset(Offset = "0x1C")]
  public Text Txt_Yes;
  [Token(Token = "0x4000C81")]
  [FieldOffset(Offset = "0x20")]
  public UIUtility.DialogResultEvent OnClickYes;
  [Token(Token = "0x4000C82")]
  [FieldOffset(Offset = "0x24")]
  public UIUtility.DialogResultEvent OnClickNo;
  [Token(Token = "0x4000C83")]
  [FieldOffset(Offset = "0x28")]
  public bool AutoClose;

  [Token(Token = "0x6000FD7")]
  [Address(RVA = "0x12B1710", Offset = "0x12B0510", VA = "0x112B1710")]
  private void OnWindowClose(UIWindow window)
  {
  }

  [Token(Token = "0x6000FD8")]
  [Address(RVA = "0x12B1540", Offset = "0x12B0340", VA = "0x112B1540")]
  public void BeginClose()
  {
  }

  [Token(Token = "0x6000FD9")]
  [Address(RVA = "0x12B15E0", Offset = "0x12B03E0", VA = "0x112B15E0")]
  private void OnClickButton(GameObject obj)
  {
  }

  [Token(Token = "0x6000FDA")]
  [Address(RVA = "0x12B1450", Offset = "0x12B0250", VA = "0x112B1450")]
  private void Awake()
  {
  }

  [Token(Token = "0x6000FDB")]
  [Address(RVA = "0x5F8EB0", Offset = "0x5F7CB0", VA = "0x105F8EB0")]
  public Win_Btn_DecideCancel_FL_C()
  {
  }
}
