// Decompiled with JetBrains decompiler
// Type: Win_Btn_Decide_Flx
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: DAD16919-792A-4B52-A355-9FC67E79AC85
// Assembly location: C:\r\Tagatame-Datamine\DMM\Il2CppDumper\DummyDll\Assembly-CSharp.dll

using Il2CppDummyDll;
using UnityEngine;
using UnityEngine.UI;

#nullable disable
[Token(Token = "0x200030C")]
[AddComponentMenu("UI/Drafts/Win_Btn_Decide_Flx")]
public class Win_Btn_Decide_Flx : UIDraft
{
  [Token(Token = "0x4000C8B")]
  [FieldOffset(Offset = "0xC")]
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [Token(Token = "0x4000C8C")]
  [FieldOffset(Offset = "0x10")]
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [Token(Token = "0x4000C8D")]
  [FieldOffset(Offset = "0x14")]
  public UIUtility.DialogResultEvent OnClickYes;

  [Token(Token = "0x6000FE1")]
  [Address(RVA = "0x12B1B80", Offset = "0x12B0980", VA = "0x112B1B80")]
  private void Awake()
  {
  }

  [Token(Token = "0x6000FE2")]
  [Address(RVA = "0x12B1C20", Offset = "0x12B0A20", VA = "0x112B1C20")]
  public void BeginClose()
  {
  }

  [Token(Token = "0x6000FE3")]
  [Address(RVA = "0x12B1CC0", Offset = "0x12B0AC0", VA = "0x112B1CC0")]
  private void OnClickButton(GameObject obj)
  {
  }

  [Token(Token = "0x6000FE4")]
  [Address(RVA = "0x12B1DE0", Offset = "0x12B0BE0", VA = "0x112B1DE0")]
  private void OnWindowClose(UIWindow window)
  {
  }

  [Token(Token = "0x6000FE5")]
  [Address(RVA = "0x2ACF80", Offset = "0x2ABD80", VA = "0x102ACF80")]
  public Win_Btn_Decide_Flx()
  {
  }
}
